# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 994c94d6d1b900c60b09af207bdf2e2a5643f8c20fb11add3171a7749a5b456302b1839df721892dd4e159fc93f1539312618eea0fec933c7441a8a971cf016f

test:
  secret_key_base: ac1784905b16c81f815041250dc1af74adb4549b9e8f6957545eb6fffa8a486079cdf0d2c0f2d26e9fc59940388aaffe7fbd961b12679183acb5b3ba22bbbcaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
